### ISSUE TITLE
\Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher is not available on DatabaseServiceProvider boot

### ISSUE THREAD

**Issue by denis019** [apiato/core#100]
Apiato EventServiceProvider (\Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher) has been registered on ApiatoProvider boot method
https://github.com/apiato/core/blob/master/Providers/ApiatoProvider.php#L80
which cause the bug that Apiato Dispatcher is not available on DatabaseServiceProvider boot method https://github.com/illuminate/database/blob/master/DatabaseServiceProvider.php#L25
so instead the Apiato Dispatcher we are getting Illuminate\Events\Dispatcher

The solution will be to register Apiato EventServiceProvider before booting.
This issue is related with https://github.com/apiato/apiato/issues/428

**Comment by johannesschobel** [comment]
this should be fixed with #101 .. can you confirm this and then close the issue @denis019 !?

Thank you very much for reporting this issue and providing a PR to address and fix this issue! :+1:
