### ISSUE TITLE
Api Version

### ISSUE THREAD

**Issue by lloricode** [apiato/core#112]
Hi!, it is possible to disable a old `api version`?

then set a redirect to a set up or active version,

sample, 
the `http://me.com/v1/test` is disabled, then it will redirect to `http://me.com/v2/test`

**Comment by johannesschobel** [comment]
Hey,
no, this is currently not possible...

I would do this "manually": For example, add a `redirect()` in the respective `Controller` method. It is most likely the case, that you want to "disable" endpoints "one by one" and migrate them to a v2 method..

**Comment by lloricode** [comment]
what about we can set this, ignore other version except  the active version


### Apiato\Core\Loaders\RoutesLoaderTrait;
```php
    /**
     * @param      $endpointFileOrPrefixString
     * @param null $controllerNamespace
     *
     * @return  array
     */
    public function getRouteGroup($endpointFileOrPrefixString, $controllerNamespace = null)
    {


        // here we can ignore old version
        $verion = $this->getApiVersionPrefix($endpointFileOrPrefixString);
        // get the active version on config?
        // logic here
        // -----------------

        return [
            'namespace'  => $controllerNamespace,
            'middleware' => $this->getMiddlewares(),
            'domain'     => $this->getApiUrl(),
            // if $endpointFileOrPrefixString is a file then get the version name from the file name, else if string use that string as prefix
            'prefix'     =>  is_string($endpointFileOrPrefixString) ? $endpointFileOrPrefixString :  $this->getApiVersionPrefix($endpointFileOrPrefixString),
        
```

**Comment by johannesschobel** [comment]
that would mean, that you will need to **completely** disable an existing version.. what about, if you want to have 2 versions in parallel and so on?

honestly, i think, i would leave this up to the developer..

The most easy approach would be to simply delete the `v1` routes - this would make specific controller methods not accessible anymore..

**Comment by lloricode** [comment]
oh i see :) thanks @johannesschobel

**Comment by johannesschobel** [comment]
if i have time (haha) i can think about a more generic approach to disable existing versions.. however, i think, this would result in a configuration-hell.. Currently, "generating" new versions is quite easy as you only need to execute the `RouteGenerator` and you are fine.. Apiato does not "know" about this version in particular (i.e., it is not "configured" in some way).. That would be required, however, in order to "disable" specific versions..

If one would need to implement this, however, the `RoutesLoaderTrait` you already mentioned would be the appropriate place ;)

**Comment by johannesschobel** [comment]
I can imagine, that "release management" in APIs is quite difficult (i.e., do you have many versions in parallel, do you try to migrate one endpoint by another one, do you try to re-implement everything and deploy at once, ...) 

I don't think there is a solid "one approach fits all" technique.. but that is just my humble opinon..

If i need to release a v2 of my api, i would probably try to do it "step by step".
