### ISSUE TITLE
Authentication testing environment

### ISSUE THREAD

**Issue by lloricode** [apiato/core#118]
Hi, it is possible to set authentication (`$this->getTestingUser()`) with seeded user?
like this
```php
      
      $user = User::find($id);
      $this->getTestingUser($user);

```

to test the specific role of possible access,

because the `$this->getTestingUser();` is create fresh without any ralation on seeded data on other model

**Comment by johannesschobel** [comment]
why would you need to create a `testingUser` when you already have a "real" `User`? Not really clear to me, haha

**Comment by lloricode** [comment]
because of i have seeded user that has already relationship seeded also to
another models, while the on apiato tesing user is frashly created while
without any relationship on other models,

i have a unit/feature test that need to check user policy on every resources

hmmm, so nit i have only solution

so i called the protected attribute from auth testing trait then set the
user to it, then acting it as authenticated, so core will skip creating
user factory

**Comment by johannesschobel** [comment]
i don't really like the approach of adding this functionality to the already existing function as this might break other code..
what about adding a new function to "inject" an existing user?

**Comment by lloricode** [comment]
yes, that much better i think

**Comment by johannesschobel** [comment]
I'll close the existing PR

**Comment by lloricode** [comment]
yes 😊😊😊

**Comment by lloricode** [comment]
Hi can i submit PR for you idea?

**Comment by johannesschobel** [comment]
Yes

Lloric Mayuga Garcia <notifications@github.com> schrieb am Fr., 27. Juli
2018, 00:43:
