### ISSUE TITLE
Only hashed ids allowed issue

### ISSUE THREAD

**Issue by deniskoronets** [apiato/core#140]
if (is_numeric($id)) {
            throw new IncorrectIdException('Only Hashed ID\'s allowed' . (!is_null($parameter) ? " ($parameter)." : '.'));
        }

this piece of code makes it impossible to decode "01" hash which is 6 in decimal. 
https://github.com/apiato/core/blob/master/Traits/HashIdTrait.php#L195

**Comment by moslem-deris** [comment]
This problem has been resolved in https://github.com/apiato/core/pull/136
