### ISSUE TITLE
Error on container creation: Container already exists

### ISSUE THREAD

**Issue by Gigiart** [apiato/core#147]
### Description:
On container creation php artisan apiato:generate:container:
Generating Composer File
Container generated successfully.
Generating Composer File
Container already exists

### Expected Behavior:
no error expected

### Versions:
- Apiato Version: 10.0.0
- PHP Version: 7.4.2

### Steps To Reproduce:
1. Create new container:  php artisan apiato:generate:container
2. Create new AppSection
Last lines upon creation show:![Capture](https://user-images.githubusercontent.com/53076936/116105059-def13b80-a6a8-11eb-8ab9-c1dbab50b0b5.PNG)

**Comment by Mohammad-Alavi** [comment]
This is not a breaking bug but more of an improvement. 
In container creation process the existence of container is checked twice and the error is thrown because of that but the files are created nevertheless.
This error is more like a warning 🤔 

PR's are welcome.
