### ISSUE TITLE
invoked route bug

### ISSUE THREAD

**Issue by Victorlerner** [apiato/core#174]
Hi, you need to remove the namespace array item from Loaders\RoutesLoaderTrait.php in method getRouteGroup.  Since you provide the wrong namespace, and actually it's a file path so it's a trigger bug. when I want in any route do this ` route::get('/test',TestCalls::class)` it will throw this exception `UnexpectedValueException : Invalid route action: `
![image](https://user-images.githubusercontent.com/26815991/219714469-8697c16b-7fe3-4fef-873a-ec9f8cbb6e1c.png)

**Comment by Mohammad-Alavi** [comment]
You are totally correct. 
It is fixed in core v8 but thanks for pointing it out 😺 
Ill fix it in core v7 if I can find the time to do it.
