### ISSUE TITLE
Call to a member function hasPermissionTo() on null

### ISSUE THREAD

**Issue by Ibragim091986** [apiato/core#192]
### Apiato Core Version

8.7.0

### PHP Version

8.2

### Description

https://github.com/apiato/core/blob/149282fbd6bfe54dfefc6e14d8142834b9612fab/Abstracts/Requests/Request.php?plain=1#L128-L140

This method triggers a "Call to a member function hasPermissionTo() on null" error if the middleware is removed from the Route, for example.

![1](https://github.com/apiato/core/assets/5635337/1aecfbfd-4cc4-461b-a873-6ab1504444b7)

And if there is any value in the Permissions block in the Request.

![2](https://github.com/apiato/core/assets/5635337/d9711dc5-8a86-4e07-85db-e577bf166e18)

I think the solution would be to check for the existence of $user in the closure before passing it to the anonymous function.

https://github.com/apiato/core/blob/149282fbd6bfe54dfefc6e14d8142834b9612fab/Abstracts/Requests/Request.php?plain=2#L137-L139

### Steps To Reproduce

1. Set values for checking in the Permissions block in the Request.
![2](https://github.com/apiato/core/assets/5635337/7170668e-36df-4f64-af13-fc9e5f9d601f)
2. Remove the middleware method from the Route if it exists.
![1](https://github.com/apiato/core/assets/5635337/2d1c5b01-c40d-43e9-9aa6-560c20fe2005)
3. Pass this Request to a WebController.
![3](https://github.com/apiato/core/assets/5635337/33a36ae8-d5b0-4178-b95f-1d3cd1cc93a6)
4. Make a request to this Route.

**Comment by Mohammad-Alavi** [comment]
Hey @Ibragim091986,
Thanks for the time you put into writing this detailed issue. 💯 

This is fixed in the latest versions. Do a `composer update` and you will have it 💪
