### ISSUE TITLE
Fix Problem with Migration in Generator

### ISSUE THREAD

**Issue by johannesschobel** [apiato/core#22]
If you run the `php artisan apiato:generate:container:api` command several times, multiple migration files are generated. I already have an idea how to fix it - need time to implement it..

This is just a friendly reminder for myself in order to fix it ;)

@Mahmoudz can you please assign me to this task?

**Comment by Mahmoudz** [comment]
@johannesschobel was about to open that issue and assign you :)

**Comment by johannesschobel** [comment]
this is now more some kind of a `ToDo` List for me:
- [ ] fix the `Migration` file bug explained above
- [ ] add a `README.md` file to the generated container

**Comment by johannesschobel** [comment]
I am working on this.. not sure when i am able to make the PR.. but i will keep you updated..
Feel free to add additional things to this list..
