### ISSUE TITLE
TestAuthHelperTrait does too much magic

### ISSUE THREAD

**Issue by Kyslik** [apiato/core#46]
I think createTestingUser method does too much magic behind the scenes.

For example [this line](https://github.com/apiato/core/blob/master/Traits/TestsTraits/PhpUnit/TestsAuthHelperTrait.php#L107) I don't think this is the best idea... Now in real tests you have to call [`$this->actingAs($user,'web')`](https://github.com/apiato/apiato/blob/master/app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php#L36) in order to "disable" the linked line.

I expect the method to "create user" not "create and authenticate it". Or just make it protected so users (developers) can override.

**Comment by Kyslik** [comment]
https://github.com/apiato/core/blob/master/Traits/TestsTraits/PhpUnit/TestsAuthHelperTrait.php#L113-L154

Now user of Apiato can not have its own table structure, what is my user does not have name? Its going to throw up.

**Comment by johannesschobel** [comment]
Apiato ships with a pre-defined set of attributes for some models (e.g., the user model). The test cases reflect those attributes..

If you don't have a name, you can remove them (from the migration file and model) and adapt your tests..

However, I would recommend to still use the username and just "hide" it in respective Transformer in order to comply with the default version of Apiato..

**Comment by Kyslik** [comment]
No its not possible. TestsAuthHelperTrait is used in Core PHPUnit class which is later used in Abstract class (Ship). In private methods (see link above) attributes are hard-coded, User model factory is hardcoded as well.

**Comment by johannesschobel** [comment]
hm, you're right.. however, this might be a bigger change?! not sure about it yet.. 

however, for now, i would suggest to keep "name" as an attribute for you ;9

**Comment by Kyslik** [comment]
What I did is the following:

```php
function factoryCreateUser($userDetails = null)
{
    return is_null($userDetails) ? factory(User::class)->create() : factory(User::class)->create($userDetails);
}
```

As you can see I do not need shenanigans with preparing password & details, I trust myself that I will send only `array` -> thus `factory` will do its thing.

To be even more modular I would use not `User::class` at all but whatever class is stored in config file auth.php -> providers -> users -> model

---
Simplest solution is to change visibility of methods within the Trait to `public` so user can do whatever.

**Comment by johannesschobel** [comment]
wouldn't setting the `factoryCreateUser()` method to `protected` solve your issue?
