### ISSUE TITLE
Apiato caller style (containerName@className) warning message

### ISSUE THREAD

**Issue by fosron** [apiato/core#47]
The error message `It is recommended to use the apiato caller style (containerName@className) for` gets really annoying and fills up the log, and we do not mind having containers "linked" (as this is the main reason i can see by reading docs http://docs.apiato.io/miscellaneous/magical-call/ for this call style). It would be good to have an option to turn off this and other future "nice to have" warning errors.

Maybe there's another way around this, but having some other error messages with warning, that do matter, changing log level app-wide is not an option. Maybe we should change this to debug/info level?

**Comment by fosron** [comment]
P.S I could do a PR for this, the question here is more about where will Apiato heading with this.

**Comment by johannesschobel** [comment]
I think, that would be a nice idea to have different "log levels" (e.g., DEBUG, INFO, WARN, ERROR) so the developer can decide on which level he would like to log (e.g., selecting `INFO` will log `INFO` and above)..

The `it is recommended to use..` message would be `DEBUG` for me..

Cheers

**Comment by Mahmoudz** [comment]
Closed by #49
