### ISSUE TITLE
ApiatoExceptionsHandler needs refactoring

### ISSUE THREAD

**Issue by Mahmoudz** [apiato/core#6]
The ugly file
https://github.com/apiato/core/blob/master/Exceptions/ApiatoExceptionsHandler.php

Worth checking this as well
https://github.com/apiato/core/blob/master/Abstracts/Exceptions/Exception.php

**Comment by johannesschobel** [comment]
if you merge [this PR here](https://github.com/apiato/core/pull/25) you can close this issue ;)
