### ISSUE TITLE
Apiato::call fails to set UI

### ISSUE THREAD

**Issue by johannesschobel** [apiato/core#61]
When calling an `Action` or `Task` by using `Apiato::call('Container@ActionOrTask')` this fails to set the `UI` correctly (is set to `null`).

This is because of the `CallableTrait::setUIIfExists()`..

This method tries to read `property_exists($this, 'ui')`. However, in the context of calling it via `Apiato::call()`, the `$this` is `Apiato` and not the corresponding container.. Therefore, this fails..

Not a major bug, but anyway ;)

**Comment by Mahmoudz** [comment]
I added feature, cause I thought it might be helpful. I never used it. And I know there are some cases it wont work, especially when the user has the option to not use the call method to invoke an Action. So feel free to delete that feature if you want. Unless anyone is heavily relying on it!

**Comment by johannesschobel** [comment]
I just wanted to add it to the issues, so i don't forget it ;) I will not try to fix it in the `DTO` patch, but rather in a later one... ;) When still calling `$this->call(...)` it will work...
