### ISSUE TITLE
Class 'Apiato\Core\Abstracts\ValueObjects\ValueObject' not found

### ISSUE THREAD

**Issue by Macias67** [apiato/core#73]
After making a `composer update` this error appeared. I deleted the vendor folder and rerun `composer install` again but without any results.

**Comment by johannesschobel** [comment]
Hey @Macias67 .. please take a look at the issues mentioned here https://github.com/apiato/apiato/issues/352 and https://github.com/apiato/apiato/issues/334 ... 

For now, please refactor your `ValueObject` in your main project to `Value` - this should do the trick for you..
