### ISSUE TITLE
TestsAuthHelperTrait not returning User with roles

### ISSUE THREAD

**Issue by Nesh83** [apiato/core#84]
It happens that setupTestingUserAccess is not returning fresh copy of users with roles.
https://github.com/apiato/core/blob/0f02f4c938e69d095c2234391db5bc1bd7518474/Traits/TestsTraits/PhpUnit/TestsAuthHelperTrait.php#L171-L179

To make my test pass I had to change `return $user;` to `return $user->fresh();`

**Comment by johannesschobel** [comment]
which test fails for you?

**Comment by Nesh83** [comment]
All Apiato tests pass but as I could see none of them have roles set in $access. When I try to set admin role for test user and admin role in Request it returns an authorized access

**Comment by Nesh83** [comment]
@johannesschobel Thanks, that is helpful for now, but it would be better if apiato/core take care of it.

**Comment by johannesschobel** [comment]
This would, however, be a breaking change for all existing users!

**Comment by huy-tran** [comment]
I fixed the issue by using `$this->actingAs($user->fresh(), 'api');` inside `createTestingUser` private method.

That's great if you can fix this in the next release.
