### ISSUE TITLE
FactoriesLoaderTrait fail to load factories while testing using ssh on laradock

### ISSUE THREAD

**Issue by Nesh83** [apiato/core#85]
My Apiato App is running on Laradock. For testing, I use PhpStorm and ssh to laradock. Problem occurs because in my case $newFactoriesPath already has base_path() included and later it gets prepended again. 
Had to change 
https://github.com/apiato/core/blob/0f02f4c938e69d095c2234391db5bc1bd7518474/Loaders/FactoriesLoaderTrait.php#L25
into 
`$newFactoriesPath = str_replace_first(base_path(), '', $loadersDirectory) . '/FactoryMixer';`

**Comment by johannesschobel** [comment]
As far as i can understand from your description, this is an issue with your configuration and not apiato itself, right?

**Comment by Nesh83** [comment]
Issue is manifested in my configuration, but it is in apiato because testing needs to work on different configurations.

**Comment by johannesschobel** [comment]
would it help to simply adjust the `phpunit.xml` configuration file in your own project?

**Comment by Nesh83** [comment]
@johannesschobel I could try. Do You have any suggestion how?

**Comment by johannesschobel** [comment]
you can add new (or overwrite existing) `env` values in the `phpunit.xml` file. Take a look at the existing file in order to see how this is specified. Maybe this will help / solve your issue?!

Normally, you should define your custom configuration for the test-environment in this file. However, you may want to check out PHPUnit itself and see if there may be other possibilities to set specific variables..

**Comment by johannesschobel** [comment]
any update on this @Nesh83 ?

**Comment by Nesh83** [comment]
@johannesschobel Had no luck in making it work by changing an environment.

**Comment by jjag3r** [comment]
I have the same problem. When I dd() those variables I get this:
```
$loadersDirectory = str_replace(getcwd(), '', __DIR__);
dump(getcwd());
dump(__DIR__);
dump($loadersDirectory);
dd($loadersDirectory);
```

> "/Users/jurejager/Code/api.webshop/app/Containers/Address/UI/API/Tests/Functional"
"/Users/jurejager/Code/api.webshop/vendor/apiato/core/Loaders"
"/Users/jurejager/Code/api.webshop/vendor/apiato/core/Loaders"
"/Users/jurejager/Code/api.webshop/vendor/apiato/core/Loaders"

`getcwd()` is not returning correct string when testing.

Like @Nesh83 said, I have changed from:
`  $newFactoriesPath = $loadersDirectory . '/FactoryMixer'; `
to 
`$newFactoriesPath = str_replace_first(base_path(), '', $loadersDirectory) . '/FactoryMixer';`
and now it works.

How can I fix this by changing `phpunit.xml`?
