### ISSUE TITLE
Array in argument and still check in body (abstract exception)

### ISSUE THREAD

**Issue by mishbah** [apiato/core#90]
we know on line 155 have `array` at `$errors` argument
https://github.com/apiato/core/blob/571c6b27e9d1e756404a198c7d5c153e9f94fc9a/Abstracts/Exceptions/Exception.php#L155

but why still check (`is_array`) at line 157 ?
https://github.com/apiato/core/blob/571c6b27e9d1e756404a198c7d5c153e9f94fc9a/Abstracts/Exceptions/Exception.php#L157

just asking...

**Comment by johannesschobel** [comment]
Better safe than sorry, I guess.. ;)
