### ISSUE TITLE
why we override tearDown method

### ISSUE THREAD

**Issue by mishbah** [apiato/core#91]
As you can see, apiato override `tearDown` method

https://github.com/apiato/core/blob/571c6b27e9d1e756404a198c7d5c153e9f94fc9a/Abstracts/Tests/PhpUnit/TestCase.php#L54

I think, we don't need to refresh database, cause `Illuminate\Foundation\Testing\TestCase` done with it, you can see at `tearDown` method at `Illuminate\Foundation\Testing\TestCase`

PS: I have tried to test it (with remove `tearDown` method in `Apiato\Core\Abstracts\Tests\PhpUnit\TestCase`), and it work (using file or `:memory` db)

**Comment by johannesschobel** [comment]
@mishbah 
the `tearDown()` function directly executes `artisan migrate:reset` if it is an in-memory database (e.g., it resets the database to an empty state!)..
If it is **not** an in-memory database, the regular `tearDown()` method will be called.. This may do some other stuff.. However, the database is not resetted, i think..

Changing this behaviour **may** result in "not clearing" the database - leading to false states in the database (depending on the execution order of tests).

_Personal Opinion:_
> I think, it is good behaviour to reset the database after a test has been executed in order to avoid a potentially corrupt state in the database (which may cause other tests to fail!)

**Comment by mishbah** [comment]
why I remove the method, cause in this line
https://github.com/apiato/core/blob/182d94342845fa3f497062d1c2a8e57b92a79f0a/Abstracts/Tests/PhpUnit/TestCase.php#L91

so, we don't need to reset the db, cause `refreshTestDatabase` method called every time we run the test...

so in detail if we override `tearDown()` method and executes two thing:
- `migrate:reset`
- `migrate:fresh`

and in my opinion, we just short this thing only 1 command (`migrate:fresh`)

**Comment by mishbah** [comment]
In another word, this line
https://github.com/apiato/core/blob/571c6b27e9d1e756404a198c7d5c153e9f94fc9a/Abstracts/Tests/PhpUnit/TestCase.php#L57
make sense

if `refreshTestDatabase` method execute `$this->artisan('migrate');` rather than `$this->artisan('migrate:fresh');`

**Comment by johannesschobel** [comment]
Hey there..
not entirely sure, if i got (all) of your points.. here is, what i got so far, however:

1) in the `setUp()` method of every test case that is executed, the `refreshDatabase()` and then `refreshInMemoryDatabase()` from `\Illuminate\Foundation\Testing\RefreshDatabase` is executed. This is, because the `RefreshDatabase` trait is added somewhere in the hierarchy within the core..

2) The `refreshInMemoryDatabase()` (see 1) ), however, is overwritten in `\Apiato\Core\Abstracts\Tests\PhpUnit\TestCase`.. This method, in turn, calls internally:
   * `artisan migrate`
   * `artisan db:seed`
   * and correctly sets up passport.. 

3) Then the actual `Test` to be executed is run - this does not really matter here.. However, it is important to illustrate the actual "flow" of the execution.

4) Finally, the `tearDown()` method is called.

**Comment by mishbah** [comment]
If I read script at laravel (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Testing/RefreshDatabase.php), if the test using database in memory (`:memory`), we don't need to reset the database, but if the test using database in file (sqlite) or the other, we need to reset the database

you can compare this (`refreshInMemoryDatabase()`)
https://github.com/laravel/framework/blob/d36ae2327475f5bb352f1ef62f993a7f28627880/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L38

with this (`refreshTestDatabase()`)
https://github.com/laravel/framework/blob/d36ae2327475f5bb352f1ef62f993a7f28627880/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L50

In my opinion, why laravel (or maybe the other) do that, cause memory will lost (or something like that), and we have new memory each test, so we don't need to reset... 

that's why, you don't need to reset (`migrate:reset`) the database if you working `:memory:` database

**Comment by johannesschobel** [comment]
cant we just do this:
```php
public function tearDown() {
   parent::tearDown();
}
```
?

**Comment by mishbah** [comment]
yes, or remove entirely

and if we want to override `tearDown()` method

we can override at (`Ship`) https://github.com/apiato/apiato/blob/master/app/Ship/Parents/Tests/PhpUnit/TestCase.php

or at `Container`

**Comment by johannesschobel** [comment]
this is fixed with #92 and #93 , respectively
