### ISSUE TITLE
$error variable is never used

### ISSUE THREAD

**Issue by chenavazer** [apiato/core#96]
https://github.com/apiato/core/blob/ec6f445de583273f388f7ba7e3e1fc8265f603e7/Abstracts/Exceptions/Exception.php#L68

**Comment by chenavazer** [comment]
Should be 
        $this->errors = $this->prepareError($errors);

?

**Comment by emanuellarini** [comment]
Just created a PR for this doing same as @johannesschobel 

I am not sure but you have to implement the `responseData` method for each exception that you want to have the `errors` array calling the `$exception->getErrors()`
